version: '{build}'

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  CMAKE_GENERATOR: Visual Studio 15 2017 Win64
  CMAKE_TOOLCHAIN_FILE: c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
  VCPKG_TARGET_TRIPLET: x64-windows
  matrix:
  - PYTHON_EXECUTABLE: C:/Python37/python.exe 
    PYTHON_VERSION: 37
    DEFAULT_ENABLED: true  
  - PYTHON_EXECUTABLE: C:/Python36-x64/python.exe 
    PYTHON_VERSION: 36
    DEFAULT_ENABLED: false

# branches to build
branches:
  # whitelist
  only:
    - master
    - /.*/

install:
  - choco install -y --allow-empty-checksums swig 

#init:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
- set PATH=C:/Python37-x64/;%PATH%
- mkdir build
- cd build

build_script:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- cmake -G "%CMAKE_GENERATOR%" -DCMAKE_TOOLCHAIN_FILE="%CMAKE_TOOLCHAIN_FILE%" -DVCPKG_TARGET_TRIPLET="%VCPKG_TARGET_TRIPLET%" -DPYTHON_EXECUTABLE=%PYTHON_EXECUTABLE% ../
#- cmake ../ -DBUILD_PYTHON_WRAPPER=ON -DPYTHON_EXECUTABLE="C:/Python37/python.exe" -DPYTHON_INCLUDE_DIR="C:/Python37/include"
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- cmake --build . --target ALL_BUILD --config Release
#- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
#- devenv /build Release XIDX.sln 
