version: '{build}'

environment:
  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  CMAKE_GENERATOR: Visual Studio 15 2017 Win64
  matrix:
  - PYTHON_EXECUTABLE: C:/Python37-x64/python.exe 
    PYTHON_VERSION: 37

# branches to build
branches:
  # whitelist
  only:
    - master
    - /.*/

install:
  - choco install -y --allow-empty-checksums swig 

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
- set PATH=C:/Python37-x64/;%PATH%
- mkdir build
- cd build

build_script:
- cmake ../ -DBUILD_PYTHON_WRAPPER=ON
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- devenv /build Release XIDX.sln 