version: '{build}'

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017
  - PYTHON: C:/Python37-x64/python.exe 
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 32
#  - PYTHON: C:/Python36-x64/python.exe 
#      PYTHON_VERSION: 3.6
#      PYTHON_ARCH: 32

# branches to build
branches:
  # whitelist
  only:
    - master
    - /.*/

install:
  - choco install -y --allow-empty-checksums swig 

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
- mkdir build
- cd build

build_script:
- cmake ../ -DBUILD_PYTHON_WRAPPER=ON
- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
- devenv /build Release XIDX.sln 